Update Gebührenordnung
pep-dortmund/latex-template pull request #52
Opened 2023-02-08 20:56 UTC by maxnoe

[gebuehrenordnung.pdf](https://github.com/pep-dortmund/latex-documents/files/10689826/gebuehrenordnung.pdf)

2023-02-08 20:58 UTC, jpherdi requested changes

2023-02-08 20:58 UTC, jpherdi commented on documents/satzung/gebuehrenordnung.tex
> +Stand: Änderungen beschlossen auf der Mitgliederversammlung vim 9. November 2022.
Vim is cool but here wrong 😁

2023-02-08 21:00 UTC, maxnoe commented on documents/satzung/gebuehrenordnung.tex
> +Stand: Änderungen beschlossen auf der Mitgliederversammlung vim 9. November 2022.
thx, fixed

2023-02-09 08:49 UTC, Kevin2 approved these changes

2023-02-09 23:04 UTC, jpherdi approved these changes

2023-02-10 07:26 UTC, merged